#!/usr/bin/env bash
# write a Bash script that installs and configures HAproxy on your se
rver
sudo apt-get install -y software-properties-common
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 375-web-01 104.196.168.90:80 check
    server 375-web-02 35.196.46.172:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
