#!/usr/bin/env bash
# Bash script that configures a server to listen on a particular port [Port 80] 

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
