#!/usr/bin/env bash
# Bash Script configuring nginx to run and listen to port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
