#!/usr/bin/env bash
# Bash script that creates an RSA key pair
# The name of the created private key must be school
# The number of bits in the created key to be created 4096
# TThe created key must be protected by the passphrase betty

ssh-keygen -t rsa -f school -b 4096 -N betty
